version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/chain-bot
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_bot.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_bot.sh
      timeout: 300
      runas: root
